### ISSUE TITLE
find resource(s) id(s) by mask

### ISSUE THREAD

**Issue by simgislab** [nextgis/pyngw#12]
this works

```
resource_name = 'exif_tool_123'
resource_id = ngwapi.get_resource_id_by_name(resource_name)
```
returns an int

how about adding something like this

```
resource_name_mask = 'exif_tool*'
resource_id = ngwapi.get_resource_ids_by_namemasl(resource_name_mask)
```
returns a list of ints

**Comment by trolleway** [comment]
implemented in #11 
see examples at https://github.com/nextgis/pyngw/blob/main/README.md#search-resources
